### ISSUE TITLE
zmienne w pętli

### ISSUE THREAD

**Issue by martagandzel** [Javagda40z/Marta-Gandzel#1]
Cześć,
mam taki problem z zadaniem 5 (z pozostałych do przećwiczenia), w którym należy pobrać od użytkownika dwie liczby całkowite i na ich podstawie "wydrukować" w konsoli prostokąt. Zrobiłam tam pętlę w pętli (kod w załączniku), ale pętla ta jest nieskończona, ponieważ zmienne sczytywane od użytkownika nie aktualizują się w pętli (a przynajmniej tak mnie informuje IntelliJ).
Czy możesz proszę wskazać prawidłowe rozwiązanie tego problemu?
Pozdrawiam,
Marta

[DrukujProstokat.txt](https://github.com/Javagda40z/Marta-Gandzel/files/4469987/DrukujProstokat.txt)

**Comment by implssv** [comment]
Cześć. Intellij nie kłamie :P. Problem wynika z tego, że w drugiej pętli inkrementujesz "i" zamiast "j" czyli zamiast i++ powinno być j++ :)
